Add checks for all commands

diff --git a/scripts/enable-upgrade-notifications b/scripts/enable-upgrade-notifications
--- a/scripts/enable-upgrade-notifications
+++ b/scripts/enable-upgrade-notifications
@@ -1,6 +1,7 @@
 # enable-upgrade-notifications
 # 0Upgrade - Set upgrade notifications for all users
 # Set upgrade notifications for all users
+echo -e "Running: 0Upgrade - Set upgrade notifications for all users - ./scripts/enable-upgrade-notifications"
 
 # Add update notifier to desktop entries
 mkdir -p ~/.config/autostart
@@ -14,3 +15,9 @@ Type=Application\n\
 NoDisplay=false\n\
 X-GNOME-Autostart-Delay=60\n\
 X-Ubuntu-Gettext-Domain=update-notifier" | tee ~/.config/autostart/update-notifier.desktop > /dev/null
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-acetoneiso b/scripts/install-acetoneiso
--- a/scripts/install-acetoneiso
+++ b/scripts/install-acetoneiso
@@ -1,5 +1,12 @@
 # install-acetoneiso
 # Utilties - Install ISO images tool
 # Install ISO images tool, mount, unmount, modify. - acetoneiso
+echo -e "Running: Utilties - Install ISO images tool - ./scripts/install-acetoneiso"
 
 sudo apt-get install -y acetoneiso
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-amd-nvidia-drivers b/scripts/install-amd-nvidia-drivers
--- a/scripts/install-amd-nvidia-drivers
+++ b/scripts/install-amd-nvidia-drivers
@@ -1,6 +1,13 @@
 # install-amd-nvidia-drivers
 # Utilties - Install AMD-Nvidia graphics drivers
 # Install Install AMD-Nvidia graphics drivers
+echo -e "Running: Utilties - Install AMD-Nvidia graphics drivers - ./scripts/install-amd-nvidia-drivers"
 
-sudo apt-get install -y ubuntu-drivers-common
+sudo apt-get install -y ubuntu-drivers-common &&
 sudo ubuntu-drivers autoinstall
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-antivir b/scripts/install-antivir
--- a/scripts/install-antivir
+++ b/scripts/install-antivir
@@ -1,14 +1,21 @@
 # install-antivir
 # Useful - Install ClamAV Antivirus
 # Install and configure ClamAV Antivirus
+echo -e "Running: Useful - Install ClamAV Antivirus - ./scripts/install-antivir"
 
-sudo apt-get install -y clamav
+sudo apt-get install -y clamav &&
 
 # Update virus database
-sudo systemctl stop clamav-freshclam
-sudo freshclam
-sudo systemctl start clamav-freshclam
+sudo systemctl stop clamav-freshclam &&
+sudo freshclam &&
+sudo systemctl start clamav-freshclam &&
 
 # Install Antivirus GUI
-sudo apt-get install -y clamtk
+sudo apt-get install -y clamtk &&
 sudo sed -e 's/Exec=clamtk %F/Exec=env LC_TIME=C clamtk %F/g' -i /usr/share/applications/clamtk.desktop
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-archives-tools b/scripts/install-archives-tools
--- a/scripts/install-archives-tools
+++ b/scripts/install-archives-tools
@@ -1,7 +1,14 @@
 # install-archives-tools
 # Utilties - Install archives tools
 # Support for zip, rar, 7zip etc.
+echo -e "Running: Utilties - Install archives tools - ./scripts/install-archives-tools"
 
-sudo add-apt-repository -y multiverse
-sudo apt-get update
-sudo apt-get install -y arj cabextract p7zip-full p7zip-rar poppler-data rar unace unrar unzip zip
+sudo add-apt-repository -y multiverse &&
+sudo apt-get update &&
+sudo apt-get install -y arj cabextract p7zip-full p7zip-rar poppler-data rar unace unrar unzip zip &&
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-atom b/scripts/install-atom
--- a/scripts/install-atom
+++ b/scripts/install-atom
@@ -1,9 +1,16 @@
 # install-atom
 # IDE - Install Atom.io IDE
 # Install easy to customize IDE – Atom.io
+echo -e "Running: IDE - Install Atom.io IDE - ./scripts/install-atom"
 
 ## Source: https://flight-manual.atom.io/getting-started/sections/installing-atom/
-wget -qO - https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
-sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'
-sudo apt-get update
+wget -qO - https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add - &&
+sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list' &&
+sudo apt-get update &&
 sudo apt-get install -y atom
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-battery-support b/scripts/install-battery-support
--- a/scripts/install-battery-support
+++ b/scripts/install-battery-support
@@ -1,7 +1,14 @@
 # install-battery-support
 # Hardware - Install better laptop's battery support
 # Install better laptop's battery support. Recommended on laptops.
+echo -e "Running: Hardware - Install better laptop's battery support - ./scripts/install-battery-support"
 
-sudo apt-get install -y tlp tlp-rdw
-sudo tlp start
+sudo apt-get install -y tlp tlp-rdw &&
+sudo tlp start &&
 sudo tlp-stat
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-bleachbit b/scripts/install-bleachbit
--- a/scripts/install-bleachbit
+++ b/scripts/install-bleachbit
@@ -1,5 +1,12 @@
 # install-bleachbit
 # Utilties - Install Bleachbit cleaner.
 # Install Bleachbit powerful cache, temp files and garbage cleaner.
+echo -e "Running: Utilties - Install Bleachbit cleaner. - ./scripts/install-bleachbit"
 
 sudo apt-get install -y bleachbit
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-calibre b/scripts/install-calibre
--- a/scripts/install-calibre
+++ b/scripts/install-calibre
@@ -1,5 +1,12 @@
 # install-calibre
 # Documents - Install ebook reader
 # Install ebook reader – calibre
+echo -e "Running: Documents - Install ebook reader - ./scripts/install-calibre"
 
 sudo apt-get install -y calibre
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-cd-dvd-burner b/scripts/install-cd-dvd-burner
--- a/scripts/install-cd-dvd-burner
+++ b/scripts/install-cd-dvd-burner
@@ -1,5 +1,12 @@
 # install-cd-dvd-burner
 # Utilties - Install CD-DVD burner
 # Install CD-DVD burner – if you have disk drive
+echo -e "Running: Utilties - Install CD-DVD burner - ./scripts/install-cd-dvd-burner"
 
 sudo apt-get install -y brasero
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-cinnamon b/scripts/install-cinnamon
--- a/scripts/install-cinnamon
+++ b/scripts/install-cinnamon
@@ -1,5 +1,12 @@
 # install-cinnamon
 # System - Install Cinnamon desktop manager
 # Install Cinnamon desktop manager
+echo -e "Running: System - Install Cinnamon desktop manager - ./scripts/install-cinnamon"
 
 sudo apt-get install -y cinnamon-core
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-codecs b/scripts/install-codecs
--- a/scripts/install-codecs
+++ b/scripts/install-codecs
@@ -1,8 +1,15 @@
 # install-codecs
 # Utilties - Install codecs
 # Codecs to support common audio, video formats and additional fonts.
+echo -e "Running: Utilties - Install codecs - ./scripts/install-codecs"
 
-sudo add-apt-repository -y multiverse
-sudo apt-get update
-echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
+sudo add-apt-repository -y multiverse &&
+sudo apt-get update && 
+echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections &&
 sudo apt-get install -y ubuntu-restricted-extras
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-czkawka b/scripts/install-czkawka
--- a/scripts/install-czkawka
+++ b/scripts/install-czkawka
@@ -1,6 +1,7 @@
 # install-czkawka
 # Utilties - Install duplicate finder czkawka. (using AppImage)
 # Install duplicate finder czkawka. (using AppImage)
+echo -e "Running: Utilties - Install duplicate finder czkawka. (using AppImage) - ./scripts/install-czkawka"
 
 ## Source https://github.com/qarmin/czkawka
 
@@ -8,14 +9,14 @@ CZKAWKA_VERSION="5.0.0"
 APPIMAGES_PATH="/home/$USER/.local/bin"
 
 ## Create directory for AppImage images
-mkdir -p $APPIMAGES_PATH
+mkdir -p $APPIMAGES_PATH &&
 
 ## Add PATH for AppImage entries
 echo -e "# Setup AppImage
 # ---------
 if [[ ! \"\$PATH\" == *$APPIMAGES_PATH* ]]; then
   export PATH=\"\${PATH:+\${PATH}:}$APPIMAGES_PATH\"
-fi" > /home/$USER/.appimage.bash
+fi" > /home/$USER/.appimage.bash &&
 
 ## AppImage entry to .bashrc (if not exist)
 if ! grep -Fxq "[ -f ~/.appimage.bash ] && source ~/.appimage.bash" /home/$USER/.bashrc
@@ -25,13 +26,13 @@ then
 fi
 
 ## Download AppImage
-wget -P /tmp https://github.com/qarmin/czkawka/releases/download/$CZKAWKA_VERSION/linux_czkawka_gui.AppImage
-mv /tmp/linux_czkawka_gui.AppImage $APPIMAGES_PATH
-chmod +x $APPIMAGES_PATH/linux_czkawka_gui.AppImage
+wget -P /tmp https://github.com/qarmin/czkawka/releases/download/$CZKAWKA_VERSION/linux_czkawka_gui.AppImage &&
+mv /tmp/linux_czkawka_gui.AppImage $APPIMAGES_PATH &&
+chmod +x $APPIMAGES_PATH/linux_czkawka_gui.AppImage &&
 
 ## Download icon
-wget -O /tmp/czkawka.svg https://raw.githubusercontent.com/qarmin/czkawka/master/data/icons/com.github.qarmin.czkawka.svg
-mv /tmp/czkawka.svg $APPIMAGES_PATH/
+wget -O /tmp/czkawka.svg https://raw.githubusercontent.com/qarmin/czkawka/master/data/icons/com.github.qarmin.czkawka.svg &&
+mv /tmp/czkawka.svg $APPIMAGES_PATH/ &&
 
 ## Add firejail configuration (if installed and user is able to use firejail) for AppImage
 if [[ $(dpkg-query -W -f='${Status}' firejail 2>/dev/null | grep -c "ok installed") -eq 1 ]] && [[ `cat /etc/firejail/firejail.users` == *$USER* ]];
@@ -42,7 +43,7 @@ else
 fi
 
 ## Integrate Czkawka AppImage with desktop
-mkdir -p /home/$USER/.local/share/applications
+mkdir -p /home/$USER/.local/share/applications &&
 echo -e "[Desktop Entry]\n\
 Type=Application\n\
 Name=Czkawka\n\
@@ -50,3 +51,9 @@ Icon=$APPIMAGES_PATH/czkawka.svg\n\
 Exec=$APPIMAGE_EXEC\n\
 Terminal=false\n\
 Comment=Multi functional app to find duplicates, empty folders, similar images etc." | tee /home/$USER/.local/share/applications/czkawka.desktop > /dev/null
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-dia b/scripts/install-dia
--- a/scripts/install-dia
+++ b/scripts/install-dia
@@ -1,5 +1,12 @@
 # install-dia
 # Graphics - Install Dia – diagram creator
 # Install Dia – diagram creator – easy and powerful
+echo -e "Running: Graphics - Install Dia – diagram creator - ./scripts/install-dia"
 
 sudo apt-get install -y dia
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-digikam b/scripts/install-digikam
--- a/scripts/install-digikam
+++ b/scripts/install-digikam
@@ -1,5 +1,12 @@
 # install-digikam
 # Photos - Install Digikam
 # Install Powerful tool for photos managment
+echo -e "Running: Photos - Install Digikam - ./scripts/install-digikam"
 
 sudo apt-get install -y digikam
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-dropbox b/scripts/install-dropbox
--- a/scripts/install-dropbox
+++ b/scripts/install-dropbox
@@ -1,14 +1,15 @@
 # install-dropbox
 # Storage - Install Dropbox client
 # Install official Dropbox client with nemo support. Headless moder – run as user which will be using dropbox.
+echo -e "Running: Storage - Install Dropbox client - ./scripts/install-dropbox"
 
 ## More information: https://www.dropbox.com/install-linux
 
 # Install official Dropbox client. Headless moder – run as user which will be using dropbox.
-cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
+cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf - &&
 
 # Add Dropbox to user's environment autostart (with Gnome panel icon fix)
-mkdir -p ~/.config/autostart
+mkdir -p ~/.config/autostart &&
 echo -e "[Desktop Entry]\n\
 Type=Application\n\
 Name=Dropbox\n\
@@ -28,3 +29,9 @@ Comment=Start Dropbox at log in" | tee ~/.config/autostart/dropbox.desktop > /de
 # # Firstrun dropbox daemon and then kill it to not freeze configuration script
 # ~/.dropbox-dist/dropboxd & sleep 10
 # killall dropbox*
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-fzf b/scripts/install-fzf
--- a/scripts/install-fzf
+++ b/scripts/install-fzf
@@ -1,25 +1,29 @@
 # install-fzf
 # Utilties - Install fzf – CLI fuzzy finder
 # Install fzf – CLI fuzzy finder. Git clone installation – run as user which will be using script
+echo -e "Running: Utilties - Install fzf – CLI fuzzy finder - ./scripts/install-fzf"
 
-git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
-~/.fzf/install --all
+git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf &&
+~/.fzf/install --all &&
 
 # Install silversearch - more powerfull searcher
-if [ $(dpkg-query -W -f='${Status}' silversearcher-ag 2>/dev/null | grep -c "ok installed") -eq 0 ];
-then
-  sudo apt-get install -y silversearcher-ag
-fi
+sudo apt-get install -y silversearcher-ag &&
 
 # Add fzf-ag support in .bashrc file
 echo -e "export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g \"\"'
 export FZF_CTRL_T_COMMAND='ag --hidden --ignore .git -g \"\"'
-export FZF_ALT_C_COMMAND='find . -type d -iname \"*\"'" >> ~/.bashrc
-source ~/.bashrc
+export FZF_ALT_C_COMMAND='find . -type d -iname \"*\"'" >> ~/.bashrc &&
+source ~/.bashrc &&
 
 # Create upgrade command in .git_upgrades directory
-mkdir -p ~/.git_upgrades
-echo "cd ~/.fzf && git pull && ./install" > ~/.git_upgrades/fzf.upgrade
-chmod +x ~/.git_upgrades/fzf.upgrade
+mkdir -p ~/.git_upgrades &&
+echo "cd ~/.fzf && git pull && ./install" > ~/.git_upgrades/fzf.upgrade &&
+chmod +x ~/.git_upgrades/fzf.upgrade &&
 # Add crontab job to auto upgrade once a week - "At 00:00 on Monday."
 crontab -l | { cat; echo "0 0 * * 1 bash ~/.git_upgrades/fzf.upgrade"; } | crontab -
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-gimp b/scripts/install-gimp
--- a/scripts/install-gimp
+++ b/scripts/install-gimp
@@ -1,5 +1,12 @@
 # install-gimp
 # Photos - Install GIMP
 # Install popular photo editor GIMP.
+echo -e "Running: Photos - Install GIMP - ./scripts/install-gimp"
 
 sudo apt-get install -y gimp gimp-data-extras gimp-plugin-registry
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-gnome-paint b/scripts/install-gnome-paint
--- a/scripts/install-gnome-paint
+++ b/scripts/install-gnome-paint
@@ -1,5 +1,12 @@
 # install-gnome-paint
 # Graphics - Install Gnome Paint - replacement for MSPaint.
 # Install Gnome Paint - Linux alternative for MSPaint.
+echo -e "Running: Graphics - Install Gnome Paint - replacement for MSPaint. - ./scripts/install-gnome-paint"
 
 sudo apt-get install -y gnome-paint
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-gnome-tools b/scripts/install-gnome-tools
--- a/scripts/install-gnome-tools
+++ b/scripts/install-gnome-tools
@@ -1,5 +1,12 @@
 # install-gnome-tools
 # Utilties - Install Gnome tools
 # Install Gnome settings managers and utils.
+echo -e "Running: Utilties - Install Gnome tools - ./scripts/install-gnome-tools"
 
 sudo apt-get install -y chrome-gnome-shell gnome-calculator gnome-system-monitor gnome-system-tools gnome-tweaks gucharmap
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-guake b/scripts/install-guake
--- a/scripts/install-guake
+++ b/scripts/install-guake
@@ -1,5 +1,12 @@
 # install-guake
 # Utilties - Install Guake – gnome dropdown terminal
 # Install Guake – gnome dropdown terminal
+echo -e "Running: Utilties - Install Guake – gnome dropdown terminal - ./scripts/install-guake"
 
 sudo apt-get install -y guake
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-hex-bless-editor b/scripts/install-hex-bless-editor
--- a/scripts/install-hex-bless-editor
+++ b/scripts/install-hex-bless-editor
@@ -1,5 +1,12 @@
 # install-hex-bless-editor
 # IDE - Install Powerful HEX editor – bless
 # Install hex editor - bless - more powerful, but needs more dependencies. – bless.
+echo -e "Running: IDE - Install Powerful HEX editor – bless - ./scripts/install-hex-bless-editor"
 
 sudo apt-get install -y bless
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-hex-gnome-editor b/scripts/install-hex-gnome-editor
--- a/scripts/install-hex-gnome-editor
+++ b/scripts/install-hex-gnome-editor
@@ -1,5 +1,12 @@
 # install-hex-gnome-editor
 # IDE - Install Simple HEX editor - ghex
 # Install simple Gnome hex editor.
+echo -e "Running: IDE - Install Simple HEX editor - ghex - ./scripts/install-hex-gnome-editor"
 
 sudo apt-get install -y ghex
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-libreoffice b/scripts/install-libreoffice
--- a/scripts/install-libreoffice
+++ b/scripts/install-libreoffice
@@ -1,6 +1,7 @@
 # install-libreoffice
 # Documents - Install Libreoffice
 # Install full Libreoffice package with language packages.
+echo -e "Running: Documents - Install Libreoffice - ./scripts/install-libreoffice"
 
 # Get system language (locale)
 SYS_LANGUAGE=`locale | grep LANG | cut -d= -f2 | cut -d_ -f1`
@@ -10,5 +11,11 @@ if [[ $SYS_LANGUAGE == "C.UTF-8" ]] ; then
   SYS_LANGUAGE="en-us"
 fi
 
-sudo add-apt-repository -y ppa:libreoffice/ppa
+sudo add-apt-repository -y ppa:libreoffice/ppa &&
 sudo apt-get install -y libreoffice-calc libreoffice-draw libreoffice-gnome libreoffice-help-$SYS_LANGUAGE  libreoffice-impress libreoffice-java-common libreoffice-l10n-$SYS_LANGUAGE libreoffice-l10n-en-gb libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-breeze libreoffice-writer
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-mkusb b/scripts/install-mkusb
--- a/scripts/install-mkusb
+++ b/scripts/install-mkusb
@@ -1,7 +1,14 @@
 # install-mkusb
 # Utilties - Install bootable live USB creator – mkusb
 # Install bootable live USB creator – mkusb
+echo -e "Running: Utilties - Install bootable live USB creator – mkusb - ./scripts/install-mkusb"
 
-sudo add-apt-repository -y ppa:mkusb/ppa
-sudo apt-get update
+sudo add-apt-repository -y ppa:mkusb/ppa &&
+sudo apt-get update &&
 sudo apt-get install -y mkusb mkusb-nox usb-pack-efi
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-ocr b/scripts/install-ocr
--- a/scripts/install-ocr
+++ b/scripts/install-ocr
@@ -1,5 +1,12 @@
 # install-ocr
 # Documents - Install OCR Reader
 # Install utilties to OCR read files.
+echo -e "Running: Documents - Install OCR Reader - ./scripts/install-ocr"
 
 sudo apt-get install -y gimagereader tesseract-ocr tesseract-ocr-pol
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-owncloud b/scripts/install-owncloud
--- a/scripts/install-owncloud
+++ b/scripts/install-owncloud
@@ -1,13 +1,20 @@
 # install-owncloud
 # Storage - Install Owncloud client
 # Install Owncloud client.
+echo -e "Running: Storage - Install Owncloud client - ./scripts/install-owncloud"
 
 ## Source: https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/
 
 ## Install dependencies:
-sudo apt-get install -y wget gnupg2 curl binutils apt-transport-https
+sudo apt-get install -y wget gnupg2 curl binutils apt-transport-https &&
 
-wget -nv https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_22.04/Release.key -O - | sudo apt-key add -
-echo 'deb https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_22.04/ /' | sudo tee -a /etc/apt/sources.list.d/owncloud.list
-sudo apt-get update
-sudo apt-get install -y owncloud-client
+wget -nv https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_22.04/Release.key -O - | sudo apt-key add - &&
+echo 'deb https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_22.04/ /' | sudo tee -a /etc/apt/sources.list.d/owncloud.list &&
+sudo apt-get update &&
+sudo apt-get install -y owncloud-client &&
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-password-manager b/scripts/install-password-manager
--- a/scripts/install-password-manager
+++ b/scripts/install-password-manager
@@ -1,7 +1,14 @@
 # install-password-manager
 # Useful - Install password manager
 # Install password manager – keepassXC
+echo -e "Running: Useful - Install password manager - ./scripts/install-password-manager"
 
-sudo add-apt-repository -y ppa:phoerious/keepassxc
-sudo apt-get update
-sudo apt-get install -y keepassxc
+sudo add-apt-repository -y ppa:phoerious/keepassxc &&
+sudo apt-get update &&
+sudo apt-get install -y keepassxc &&
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-pdf-tools b/scripts/install-pdf-tools
--- a/scripts/install-pdf-tools
+++ b/scripts/install-pdf-tools
@@ -1,6 +1,13 @@
 # install-pdf-tools
 # Documents - Install PDF tools
 # Install utilties to support pdf modifications  - merging, spliting, replacing pages etc.
+echo -e "Running: Documents - Install PDF tools - ./scripts/install-pdf-tools"
 
-sudo apt-get install -y pdfshuffler
+sudo apt-get install -y pdfshuffler &&
 sudo snap install krop
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-qalculate b/scripts/install-qalculate
--- a/scripts/install-qalculate
+++ b/scripts/install-qalculate
@@ -1,5 +1,12 @@
 # install-qalculate
 # Useful - Install Qalculate scientific calculator
 # Install Qalculate scientific calculator
+echo -e "Running: Useful - Install Qalculate scientific calculator - ./scripts/install-qalculate"
 
 sudo apt-get install -y qalculate-gtk
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-qownnotes b/scripts/install-qownnotes
--- a/scripts/install-qownnotes
+++ b/scripts/install-qownnotes
@@ -1,7 +1,14 @@
 # install-qownnotes
 # Documents - Install QownNotes
 # Install notepad with markdown support and todo list manager supporting sync.
+echo -e "Running: Documents - Install QownNotes - ./scripts/install-qownnotes"
 
-sudo add-apt-repository -y ppa:pbek/qownnotes
-sudo apt-get update
+sudo add-apt-repository -y ppa:pbek/qownnotes &&
+sudo apt-get update &&
 sudo apt-get install -y qownnotes
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-qtcreator b/scripts/install-qtcreator
--- a/scripts/install-qtcreator
+++ b/scripts/install-qtcreator
@@ -1,5 +1,12 @@
 # install-qtcreator
 # IDE - Install qtCreator IDE
 # Install IDE for qt programs
+echo -e "Running: IDE - Install qtCreator IDE - ./scripts/install-qtcreator"
 
 sudo apt-get install -y qtcreator
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-scanner-support b/scripts/install-scanner-support
--- a/scripts/install-scanner-support
+++ b/scripts/install-scanner-support
@@ -1,5 +1,12 @@
 # install-scanner-support
 # Hardware - Install scanner support
 # Install utilties to support scanner in Ubuntu.
+echo -e "Running: Hardware - Install scanner support - ./scripts/install-scanner-support"
 
 sudo apt-get install -y xsane simple-scan
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-sysadmin-network-tools b/scripts/install-sysadmin-network-tools
--- a/scripts/install-sysadmin-network-tools
+++ b/scripts/install-sysadmin-network-tools
@@ -1,5 +1,12 @@
 # install-sysadmin-network-tools
 # Network - Install sysadmin network utilties
 # Install utilties to monitor network traffic e.g. nethogs, nmap, iftop, whois, net-tools etc.
+echo -e "Running: Network - Install sysadmin network utilties - ./scripts/install-sysadmin-network-tools"
 
 sudo apt-get install -y iftop nethogs net-tools nmap whois wireshark
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-system-utilties b/scripts/install-system-utilties
--- a/scripts/install-system-utilties
+++ b/scripts/install-system-utilties
@@ -1,5 +1,12 @@
 # install-system-utilties
 # Utilties - Install useful system utilties
 # Install Partitioning tools, space usage tools, hardware info tools.
+echo -e "Running: Utilties - Install useful system utilties - ./scripts/install-system-utilties"
 
 sudo apt-get install -y baobab build-essential curl dconf-editor exfatprogs git git-lfs gparted gufw hardinfo htop incron lm-sensors mc meld ncdu printer-driver-cups-pdf silversearcher-ag sqlite3 sqlitebrowser tree unattended-upgrades
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-tellico b/scripts/install-tellico
--- a/scripts/install-tellico
+++ b/scripts/install-tellico
@@ -1,6 +1,13 @@
 # install-tellico
 # Useful - Install Tellico – collections manager
 # Install Tellico – collections manager – books, movies, coins etc.
+echo -e "Running: Useful - Install Tellico – collections manager - ./scripts/install-tellico"
 
 # http://tellico-project.org/
 sudo apt-get install -y tellico
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-virtualbox b/scripts/install-virtualbox
--- a/scripts/install-virtualbox
+++ b/scripts/install-virtualbox
@@ -1,5 +1,12 @@
 # install-virtualbox
 # Developer - Install VirtualBox
 # Install Virtualbox virtual machines manager.
+echo -e "Running: Developer - Install VirtualBox - ./scripts/install-virtualbox"
 
 sudo apt-get install -y virtualbox virtualbox-guest-additions-iso
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-vlc b/scripts/install-vlc
--- a/scripts/install-vlc
+++ b/scripts/install-vlc
@@ -1,11 +1,18 @@
 # install-vlc
 # Multimedia - Install VLC
 # Install popular media player - both music and videos.
+echo -e "Running: Multimedia - Install VLC - ./scripts/install-vlc"
 
-sudo apt-get install -y vlc
+sudo apt-get install -y vlc &&
 
 # Set as default Gnome media player
-sudo mkdir -p /etc/gnome
-sudo touch /etc/gnome/defaults.list
-sudo sed -i 's/org.gnome.Totem.desktop/vlc.desktop/g' /etc/gnome/defaults.list
+sudo mkdir -p /etc/gnome &&
+sudo touch /etc/gnome/defaults.list &&
+sudo sed -i 's/org.gnome.Totem.desktop/vlc.desktop/g' /etc/gnome/defaults.list &&
 sudo sed -i 's/rhythmbox.desktop/vlc.desktop/g' /etc/gnome/defaults.list
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/install-webcam-cheese b/scripts/install-webcam-cheese
--- a/scripts/install-webcam-cheese
+++ b/scripts/install-webcam-cheese
@@ -1,5 +1,12 @@
 # install-webcam-cheese
 # Hardware - Install webcam application
 # Install webcam application – cheese
+echo -e "Running: Hardware - Install webcam application - ./scripts/install-webcam-cheese"
 
 sudo apt-get install -y cheese
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/perform-cleanup b/scripts/perform-cleanup
--- a/scripts/perform-cleanup
+++ b/scripts/perform-cleanup
@@ -1,7 +1,14 @@
 # perform-cleanup
 # Cleanup - Clean packages
 # Perform apt autoremove, clean and autoclean
+echo -e "Running: Cleanup - Clean packages - ./scripts/perform-cleanup"
 
-sudo apt clean
-sudo apt-get autoclean
+sudo apt clean &&
+sudo apt-get autoclean &&
 sudo apt-get autoremove -y --purge
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/perform-upgrade b/scripts/perform-upgrade
--- a/scripts/perform-upgrade
+++ b/scripts/perform-upgrade
@@ -1,6 +1,13 @@
 # perform-upgrade
 # 0Upgrade - Upgrade packages
 # Perform apt dist-upgrade
+echo -e "Running: 0Upgrade - Upgrade packages - ./scripts/perform-upgrade"
 
-sudo apt-get update
+sudo apt-get update &&
 sudo apt dist-upgrade -y
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/remove-swapfile b/scripts/remove-swapfile
--- a/scripts/remove-swapfile
+++ b/scripts/remove-swapfile
@@ -1,10 +1,17 @@
 # remove-swapfile
 # Performance - Remove swapfile
 # Removing of swapfile is recommended when using ssd drive - to increase it's life. When swap is off hibernation is disabled!
+echo -e "Running: Performance - Remove swapfile - ./scripts/remove-swapfile"
 
 ## Turn off swap
-sudo swapoff -a
+sudo swapoff -a &&
 
 ## Remove swapfile
-sudo sed -i '/\/swapfile/d' /etc/fstab
+sudo sed -i '/\/swapfile/d' /etc/fstab &&
 sudo rm -f /swapfile
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/replace-gedit-pluma b/scripts/replace-gedit-pluma
--- a/scripts/replace-gedit-pluma
+++ b/scripts/replace-gedit-pluma
@@ -1,11 +1,18 @@
 # replace-gedit-pluma
 # System - Replace notepad gedit with pluma
 # Replace default gedit with powerful pluma notepad.
+echo -e "Running: System - Replace notepad gedit with pluma - ./scripts/replace-gedit-pluma"
 
-sudo apt-get install -y pluma
+sudo apt-get install -y pluma &&
 
 # Set as default notepad
-sudo sed -i 's/gedit.desktop/pluma.desktop/g' /etc/gnome/defaults.list
+sudo sed -i 's/gedit.desktop/pluma.desktop/g' /etc/gnome/defaults.list &&
 
 # Uninstall gedit
-sudo apt-get remove -y --purge gedit
+sudo apt-get remove -y --purge gedit &&
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/replace-nautilus-nemo b/scripts/replace-nautilus-nemo
--- a/scripts/replace-nautilus-nemo
+++ b/scripts/replace-nautilus-nemo
@@ -1,14 +1,15 @@
 # replace-nautilus-nemo
 # System - Replace filemanager Nautilus with Nemo
 # Replace file manager Nautilus with more powerful Nemo
+echo -e "Running: System - Replace filemanager Nautilus with Nemo - ./scripts/replace-nautilus-nemo"
 
-sudo apt-get install -y nemo nemo-fileroller
+sudo apt-get install -y nemo nemo-fileroller &&
 
 # Set nemo as main filemanager
-sudo xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search
-sudo gsettings set org.gnome.desktop.background show-desktop-icons false
-sudo gsettings set org.nemo.desktop show-desktop-icons true
-sudo xdg-mime query default inode/directory
+sudo xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search &&
+sudo gsettings set org.gnome.desktop.background show-desktop-icons false &&
+sudo gsettings set org.nemo.desktop show-desktop-icons true &&
+sudo xdg-mime query default inode/directory &&
 
 # Add desktop support - autostart command: "nemo-desktop"
 echo -e "[Desktop Entry]\n\
@@ -22,7 +23,13 @@ X-GNOME-Autostart-Phase=Desktop\n\
 X-GNOME-Autostart-Notify=true\n\
 X-GNOME-AutoRestart=true\n\
 X-GNOME-Provides=filemanager\n\
-Comment=Start Nemo desktop at log in" | sudo tee /etc/xdg/autostart/nemo-desktop.desktop > /dev/null
+Comment=Start Nemo desktop at log in" | sudo tee /etc/xdg/autostart/nemo-desktop.desktop > /dev/null &&
 
 # Remove Nautilus
 sudo apt-get remove -y --purge  nautilus nautilus-extension-gnome-terminal nautilus-sendto nautilus-share
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/replace-snap-firefox b/scripts/replace-snap-firefox
--- a/scripts/replace-snap-firefox
+++ b/scripts/replace-snap-firefox
@@ -1,15 +1,22 @@
 # replace-snap-firefox
 # Utilties - Replace firefox snap package with native apt.
 # Replace firefox snap package with native apt.
+echo -e "Running: Utilties - Replace firefox snap package with native apt. - ./scripts/replace-snap-firefox"
 
-sudo snap remove firefox
-sudo add-apt-repository -y ppa:mozillateam/ppa
+sudo snap remove firefox &&
+sudo add-apt-repository -y ppa:mozillateam/ppa &&
 echo '
 Package: * \
 Pin: release o=LP-PPA-mozillateam \
 Pin-Priority: 1001 \
-' | sudo tee /etc/apt/preferences.d/mozilla-firefox
+' | sudo tee /etc/apt/preferences.d/mozilla-firefox &&
 
-echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox
+echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox &&
 
 sudo apt -y install firefox
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/set-grub b/scripts/set-grub
--- a/scripts/set-grub
+++ b/scripts/set-grub
@@ -1,6 +1,13 @@
 # set-grub
 # System - Set Grub Timeout to 1 second
 # Set Grub Timeout to 1 second
+echo -e "Running: System - Set Grub Timeout to 1 second - ./scripts/set-grub"
 
-sudo sed -i 's/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=1/' /etc/default/grub
+sudo sed -i 's/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=1/' /etc/default/grub &&
 sudo update-grub
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
diff --git a/scripts/uninstall-ubuntu-dock b/scripts/uninstall-ubuntu-dock
--- a/scripts/uninstall-ubuntu-dock
+++ b/scripts/uninstall-ubuntu-dock
@@ -1,5 +1,12 @@
 # uninstall-ubuntu-dock
 # Cleanup - Uninstall Ubuntu dock
 # Uninstall Ubuntu Gnome dock.
+echo -e "Running: Cleanup - Uninstall Ubuntu dock - ./scripts/uninstall-ubuntu-dock"
 
 sudo apt-get remove -y --purge gnome-shell-extension-ubuntu-dock
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+else
+   echo -e "\\nFAIL\\n"
+fi
