Add support for Ubuntu 22.04 (#5)
* Update Github Actions for 22.04

* Fix actions warnings and errors

* Replace apt with apt-get

* Add exit status for all scripts

* Install `ubuntu-desktop` package to emulate Desktop version

diff --git a/scripts/enable-tmp-ram b/scripts/enable-tmp-ram
--- a/scripts/enable-tmp-ram
+++ b/scripts/enable-tmp-ram
@@ -1,5 +1,14 @@
 # enable-tmp-ram
 # Performance - Enable tmp folder in RAM
 # Increase efficiency of your system and enable tmp folder in RAM. Recommended if more than 8GB of RAM
+echo -e "Running: Performance - Enable tmp folder in RAM - ./scripts/enable-tmp-ram"
 
 sudo echo 'tmpfs  /tmp  tmpfs defaults,noatime,nosuid,nodev,mode=1777  0 0' | sudo tee -a /etc/fstab > /dev/null
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/fix-top-panel-icons b/scripts/fix-top-panel-icons
--- a/scripts/fix-top-panel-icons
+++ b/scripts/fix-top-panel-icons
@@ -1,6 +1,15 @@
 # fix-top-panel-icons
 # Fixes - Fix top panel icons
 # Fix top panel icons on systems upgraded from 16.04
+echo -e "Running: Fixes - Fix top panel icons - ./scripts/fix-top-panel-icons"
 
-sudo apt remove --purge indicator-common
+sudo apt-get remove -y --purge indicator-common &&
 sudo apt -y autoremove
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-amd-nvidia-drivers b/scripts/install-amd-nvidia-drivers
--- a/scripts/install-amd-nvidia-drivers
+++ b/scripts/install-amd-nvidia-drivers
@@ -1,6 +1,15 @@
 # install-amd-nvidia-drivers
 # Utilties - Install AMD-Nvidia graphics drivers
 # Install Install AMD-Nvidia graphics drivers
+echo -e "Running: Utilties - Install AMD-Nvidia graphics drivers - ./scripts/install-amd-nvidia-drivers"
 
-sudo apt install ubuntu-drivers-common
+sudo apt-get install -y ubuntu-drivers-common &&
 sudo ubuntu-drivers autoinstall
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-audacity b/scripts/install-audacity
--- a/scripts/install-audacity
+++ b/scripts/install-audacity
@@ -1,5 +1,14 @@
 # install-audacity
 # Multimedia - Install Audacity audio editor
 # Install Audacity audio editor
+echo -e "Running: Multimedia - Install Audacity audio editor - ./scripts/install-audacity"
 
-sudo apt install -y audacity
+sudo apt-get install -y audacity
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-backup-tools b/scripts/install-backup-tools
--- a/scripts/install-backup-tools
+++ b/scripts/install-backup-tools
@@ -1,17 +1,18 @@
 # install-backup-tools
 # Utilties - Install backup tools.
 # Install backup tools - luckybackup AKA rsync-gui and unison syncronizer.
+echo -e "Running: Utilties - Install backup tools. - ./scripts/install-backup-tools"
 
-sudo apt install -y luckybackup
+sudo apt-get install -y luckybackup &&
 
 ## Unison is installed from official repository: https://github.com/bcpierce00/unison
-wget https://github.com/bcpierce00/unison/releases/download/v2.52.0/unison-v2.52.0+ocaml-4.12.1+x86_64.linux.tar.gz -O /tmp/unison.tar.gz
-mkdir /tmp/unison
-tar -xzf /tmp/unison.tar.gz -C /tmp/unison
-sudo install -C -o root -m 755 /tmp/unison/bin/* /usr/local/bin/
+wget https://github.com/bcpierce00/unison/releases/download/v2.52.0/unison-v2.52.0+ocaml-4.12.1+x86_64.linux.tar.gz -O /tmp/unison.tar.gz &&
+mkdir /tmp/unison &&
+tar -xzf /tmp/unison.tar.gz -C /tmp/unison &&
+sudo install -C -o root -m 755 /tmp/unison/bin/* /usr/local/bin/ &&
 
-wget https://raw.githubusercontent.com/bcpierce00/unison/master/icons/U.svg -O /tmp/unison/unison.svg
-sudo install -C -o root -m 644 /tmp/unison/unison.svg /usr/share/icons/
+wget https://raw.githubusercontent.com/bcpierce00/unison/master/icons/U.svg -O /tmp/unison/unison.svg &&
+sudo install -C -o root -m 644 /tmp/unison/unison.svg /usr/share/icons/ &&
 
 # Add Unison Desktop Entry
 echo -e "[Desktop Entry]\n\
@@ -26,3 +27,11 @@ Icon=unison.svg\n\
 Categories=Utility;FileTools;GTK;\n\
 StartupWMClass=Unison-gtk\n\
 StartupNotify=true" | sudo tee /usr/share/applications/unison.desktop > /dev/null
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-battery-support b/scripts/install-battery-support
--- a/scripts/install-battery-support
+++ b/scripts/install-battery-support
@@ -1,7 +1,16 @@
 # install-battery-support
 # Hardware - Install better laptop's battery support
 # Install better laptop's battery support. Recommended on laptops.
+echo -e "Running: Hardware - Install better laptop's battery support - ./scripts/install-battery-support"
 
-sudo apt install -y tlp tlp-rdw
-sudo tlp start
+sudo apt-get install -y tlp tlp-rdw &&
+sudo tlp start &&
 sudo tlp-stat
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-bleachbit b/scripts/install-bleachbit
--- a/scripts/install-bleachbit
+++ b/scripts/install-bleachbit
@@ -1,5 +1,14 @@
 # install-bleachbit
 # Utilties - Install Bleachbit cleaner.
 # Install Bleachbit powerful cache, temp files and garbage cleaner.
+echo -e "Running: Utilties - Install Bleachbit cleaner. - ./scripts/install-bleachbit"
 
-sudo apt install -y bleachbit
+sudo apt-get install -y bleachbit
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-calibre b/scripts/install-calibre
--- a/scripts/install-calibre
+++ b/scripts/install-calibre
@@ -1,5 +1,14 @@
 # install-calibre
 # Documents - Install ebook reader
 # Install ebook reader – calibre
+echo -e "Running: Documents - Install ebook reader - ./scripts/install-calibre"
 
-sudo apt install -y calibre
+sudo apt-get install -y calibre
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-cd-dvd-burner b/scripts/install-cd-dvd-burner
--- a/scripts/install-cd-dvd-burner
+++ b/scripts/install-cd-dvd-burner
@@ -1,5 +1,14 @@
 # install-cd-dvd-burner
 # Utilties - Install CD-DVD burner
 # Install CD-DVD burner – if you have disk drive
+echo -e "Running: Utilties - Install CD-DVD burner - ./scripts/install-cd-dvd-burner"
 
-sudo apt install -y brasero
+sudo apt-get install -y brasero
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-chromium b/scripts/install-chromium
--- a/scripts/install-chromium
+++ b/scripts/install-chromium
@@ -1,5 +1,14 @@
 # install-chromium
 # Useful - Install Chromium browser
 # Install open-source Chromium browser. Open-source Chrome.
+echo -e "Running: Useful - Install Chromium browser - ./scripts/install-chromium"
 
-sudo apt install -y chromium-browser
+sudo apt-get install -y chromium-browser
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-cinnamon b/scripts/install-cinnamon
--- a/scripts/install-cinnamon
+++ b/scripts/install-cinnamon
@@ -1,5 +1,14 @@
 # install-cinnamon
 # System - Install Cinnamon desktop manager
 # Install Cinnamon desktop manager
+echo -e "Running: System - Install Cinnamon desktop manager - ./scripts/install-cinnamon"
 
-sudo apt install -y cinnamon-core
+sudo apt-get install -y cinnamon-core
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-codecs b/scripts/install-codecs
--- a/scripts/install-codecs
+++ b/scripts/install-codecs
@@ -1,8 +1,17 @@
 # install-codecs
 # Utilties - Install codecs
 # Codecs to support common audio, video formats and additional fonts.
+echo -e "Running: Utilties - Install codecs - ./scripts/install-codecs"
 
-sudo add-apt-repository -y multiverse
-sudo apt update
-echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
-sudo apt install -y ubuntu-restricted-extras
+sudo add-apt-repository -y multiverse &&
+sudo apt-get update && 
+echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections &&
+sudo apt-get install -y ubuntu-restricted-extras
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-desktop-recorder b/scripts/install-desktop-recorder
--- a/scripts/install-desktop-recorder
+++ b/scripts/install-desktop-recorder
@@ -1,5 +1,14 @@
 # install-desktop-recorder
 # Useful - Install Kazam desktop recorder
 # Install Kazam - simple desktop recorder
+echo -e "Running: Useful - Install Kazam desktop recorder - ./scripts/install-desktop-recorder"
 
-sudo apt install -y kazam
+sudo apt-get install -y kazam
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-dia b/scripts/install-dia
--- a/scripts/install-dia
+++ b/scripts/install-dia
@@ -1,5 +1,14 @@
 # install-dia
 # Graphics - Install Dia – diagram creator
 # Install Dia – diagram creator – easy and powerful
+echo -e "Running: Graphics - Install Dia – diagram creator - ./scripts/install-dia"
 
-sudo apt install -y dia
+sudo apt-get install -y dia
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-digikam b/scripts/install-digikam
--- a/scripts/install-digikam
+++ b/scripts/install-digikam
@@ -1,5 +1,14 @@
 # install-digikam
 # Photos - Install Digikam
 # Install Powerful tool for photos managment
+echo -e "Running: Photos - Install Digikam - ./scripts/install-digikam"
 
-sudo apt install -y digikam
+sudo apt-get install -y digikam
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-docker b/scripts/install-docker
--- a/scripts/install-docker
+++ b/scripts/install-docker
@@ -1,14 +1,23 @@
 # install-docker
 # Developer - Install Docker
 # Install Docker from snap package manager.
+echo -e "Running: Developer - Install Docker - ./scripts/install-docker"
 
 # Install docker snap
-sudo snap install docker
+sudo snap install docker &&
 
 # Create and join the docker group
-sudo groupadd --system docker
-sudo usermod -a -G docker $USER
+sudo groupadd -f --system docker &&
+sudo usermod -a -G docker $USER &&
 
 # Disable and re-enable the docker snap
-sudo snap disable docker
+sudo snap disable docker &&
 sudo snap enable docker
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-firejail b/scripts/install-firejail
--- a/scripts/install-firejail
+++ b/scripts/install-firejail
@@ -1,14 +1,23 @@
 # install-firejail
 # Utilties - Install sandboxing app – Firejail
 # Install sandboxing app Firejail.
+echo -e "Running: Utilties - Install sandboxing app – Firejail - ./scripts/install-firejail"
 
 ## Source: https://github.com/netblue30/firejail
 
 ## Add PPA repository for firejail
-sudo add-apt-repository -y ppa:deki/firejail
-sudo apt update
+sudo add-apt-repository -y ppa:deki/firejail &&
+sudo apt-get update &&
 
 ## Install dependencies
-sudo apt install -y git build-essential libapparmor-dev pkg-config gawk
+sudo apt-get install -y git build-essential libapparmor-dev pkg-config gawk &&
 
-sudo apt install -y firejail
+sudo apt-get install -y firejail
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-gimp b/scripts/install-gimp
--- a/scripts/install-gimp
+++ b/scripts/install-gimp
@@ -1,5 +1,14 @@
 # install-gimp
 # Photos - Install GIMP
 # Install popular photo editor GIMP.
+echo -e "Running: Photos - Install GIMP - ./scripts/install-gimp"
 
-sudo apt install -y gimp gimp-data-extras gimp-plugin-registry
+sudo apt-get install -y gimp gimp-data-extras gimp-plugin-registry
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-gnome-paint b/scripts/install-gnome-paint
--- a/scripts/install-gnome-paint
+++ b/scripts/install-gnome-paint
@@ -1,5 +1,14 @@
 # install-gnome-paint
 # Graphics - Install Gnome Paint - replacement for MSPaint.
 # Install Gnome Paint - Linux alternative for MSPaint.
+echo -e "Running: Graphics - Install Gnome Paint - replacement for MSPaint. - ./scripts/install-gnome-paint"
 
-sudo apt install -y gnome-paint
+sudo apt-get install -y gnome-paint
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-guake b/scripts/install-guake
--- a/scripts/install-guake
+++ b/scripts/install-guake
@@ -1,5 +1,14 @@
 # install-guake
 # Utilties - Install Guake – gnome dropdown terminal
 # Install Guake – gnome dropdown terminal
+echo -e "Running: Utilties - Install Guake – gnome dropdown terminal - ./scripts/install-guake"
 
-sudo apt install -y guake
+sudo apt-get install -y guake
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-hex-bless-editor b/scripts/install-hex-bless-editor
--- a/scripts/install-hex-bless-editor
+++ b/scripts/install-hex-bless-editor
@@ -1,5 +1,14 @@
 # install-hex-bless-editor
 # IDE - Install Powerful HEX editor – bless
 # Install hex editor - bless - more powerful, but needs more dependencies. – bless.
+echo -e "Running: IDE - Install Powerful HEX editor – bless - ./scripts/install-hex-bless-editor"
 
-sudo apt install -y bless
+sudo apt-get install -y bless
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-hex-gnome-editor b/scripts/install-hex-gnome-editor
--- a/scripts/install-hex-gnome-editor
+++ b/scripts/install-hex-gnome-editor
@@ -1,5 +1,14 @@
 # install-hex-gnome-editor
 # IDE - Install Simple HEX editor - ghex
 # Install simple Gnome hex editor.
+echo -e "Running: IDE - Install Simple HEX editor - ghex - ./scripts/install-hex-gnome-editor"
 
-sudo apt install -y ghex
+sudo apt-get install -y ghex
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-inkscape b/scripts/install-inkscape
--- a/scripts/install-inkscape
+++ b/scripts/install-inkscape
@@ -1,7 +1,16 @@
 # install-inkscape
 # Graphics - Install Inkscape – vector graphic editor
 # Install vector graphic editor – Inkscape
+echo -e "Running: Graphics - Install Inkscape – vector graphic editor - ./scripts/install-inkscape"
 
-sudo add-apt-repository -y ppa:inkscape.dev/stable
-sudo apt update
-sudo apt install -y inkscape
+sudo add-apt-repository -y ppa:inkscape.dev/stable &&
+sudo apt-get update &&
+sudo apt-get install -y inkscape
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-language-packages b/scripts/install-language-packages
--- a/scripts/install-language-packages
+++ b/scripts/install-language-packages
@@ -1,6 +1,7 @@
 # install-language-packages
 # Utilties - Install language packages
 # Installing language packages for your locale different than English.
+echo -e "Running: Utilties - Install language packages - ./scripts/install-language-packages"
 
 # Get system language (locale)
 SYS_LANGUAGE=`locale | grep LANG | cut -d= -f2 | cut -d_ -f1`
@@ -12,9 +13,17 @@ if [[ $SYS_LANGUAGE == "C.UTF-8" ]] ; then
   SYS_LANGUAGE2="en-us"
 fi
 
-sudo apt install -y aspell-$SYS_LANGUAGE firefox-locale-$SYS_LANGUAGE language-pack-gnome-$SYS_LANGUAGE language-pack-gnome-$SYS_LANGUAGE-base language-pack-$SYS_LANGUAGE language-pack-$SYS_LANGUAGE-base wpolish
-sudo apt install -y hyphen-$SYS_LANGUAGE2 libreoffice-help-$SYS_LANGUAGE2 libreoffice-l10n-$SYS_LANGUAGE2 mythes-$SYS_LANGUAGE2
-
 if [[ ! $SYS_LANGUAGE == "en" ]] ; then
-  sudo apt install manpages-$SYS_LANGUAGE
+  sudo apt-get install -y manpages-$SYS_LANGUAGE
+fi
+
+sudo apt-get install -y aspell-$SYS_LANGUAGE firefox-locale-$SYS_LANGUAGE language-pack-gnome-$SYS_LANGUAGE language-pack-gnome-$SYS_LANGUAGE-base language-pack-$SYS_LANGUAGE language-pack-$SYS_LANGUAGE-base wpolish &&
+sudo apt-get install -y hyphen-$SYS_LANGUAGE2 libreoffice-help-$SYS_LANGUAGE2 libreoffice-l10n-$SYS_LANGUAGE2 mythes-$SYS_LANGUAGE2 &&
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
 fi
diff --git a/scripts/install-nextcloud b/scripts/install-nextcloud
--- a/scripts/install-nextcloud
+++ b/scripts/install-nextcloud
@@ -1,13 +1,22 @@
 # install-nextcloud
 # Storage - Install Nextcloud client
 # Install Nextcloud client.
+echo -e "Running: Storage - Install Nextcloud client - ./scripts/install-nextcloud"
 
-sudo add-apt-repository -y ppa:nextcloud-devs/client
-sudo apt update
-sudo apt install -y nextcloud-client 
+sudo add-apt-repository -y ppa:nextcloud-devs/client &&
+sudo apt-get update &&
+sudo apt-get install -y nextcloud-client &&
 
 ## Install nemo integration if nemo is installed
 if [ $(dpkg-query -W -f='${Status}' nemo 2>/dev/null | grep -c "ok installed") -eq 1 ];
 then
-  sudo apt install -y nextcloud-client-nemo
+  sudo apt-get install -y nextcloud-client-nemo
+fi
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
 fi
diff --git a/scripts/install-ocr b/scripts/install-ocr
--- a/scripts/install-ocr
+++ b/scripts/install-ocr
@@ -1,5 +1,14 @@
 # install-ocr
 # Documents - Install OCR Reader
 # Install utilties to OCR read files.
+echo -e "Running: Documents - Install OCR Reader - ./scripts/install-ocr"
 
-sudo apt install -y gimagereader tesseract-ocr tesseract-ocr-pol
+sudo apt-get install -y gimagereader tesseract-ocr tesseract-ocr-pol
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-owncloud b/scripts/install-owncloud
--- a/scripts/install-owncloud
+++ b/scripts/install-owncloud
@@ -1,13 +1,22 @@
 # install-owncloud
 # Storage - Install Owncloud client
 # Install Owncloud client.
+echo -e "Running: Storage - Install Owncloud client - ./scripts/install-owncloud"
 
 ## Source: https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/
 
 ## Install dependencies:
-sudo apt install -y wget gnupg2 curl binutils apt-transport-https
+sudo apt-get install -y wget gnupg2 curl binutils apt-transport-https &&
 
-wget -nv https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_20.04/Release.key -O - | sudo apt-key add -
-echo 'deb https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_20.04/ /' | sudo tee -a /etc/apt/sources.list.d/owncloud.list
-sudo apt update
-sudo apt install -y owncloud-client
+wget -nv https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_22.04/Release.key -O - | sudo apt-key add - &&
+echo 'deb https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_22.04/ /' | sudo tee -a /etc/apt/sources.list.d/owncloud.list &&
+sudo apt-get update &&
+sudo apt-get install -y owncloud-client &&
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-password-manager b/scripts/install-password-manager
--- a/scripts/install-password-manager
+++ b/scripts/install-password-manager
@@ -1,7 +1,16 @@
 # install-password-manager
 # Useful - Install password manager
 # Install password manager – keepassXC
+echo -e "Running: Useful - Install password manager - ./scripts/install-password-manager"
 
-sudo add-apt-repository -y ppa:phoerious/keepassxc
-sudo apt update
-sudo apt install -y keepassxc
+sudo add-apt-repository -y ppa:phoerious/keepassxc &&
+sudo apt-get update &&
+sudo apt-get install -y keepassxc &&
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-pdf-tools b/scripts/install-pdf-tools
--- a/scripts/install-pdf-tools
+++ b/scripts/install-pdf-tools
@@ -1,6 +1,15 @@
 # install-pdf-tools
 # Documents - Install PDF tools
 # Install utilties to support pdf modifications  - merging, spliting, replacing pages etc.
+echo -e "Running: Documents - Install PDF tools - ./scripts/install-pdf-tools"
 
-sudo apt install -y pdfshuffler
+sudo apt-get install -y pdfarranger &&
 sudo snap install krop
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-photo-utils b/scripts/install-photo-utils
--- a/scripts/install-photo-utils
+++ b/scripts/install-photo-utils
@@ -1,5 +1,14 @@
 # install-photo-utils
 # Photos - Install batch photos utilties
 # Install utilties to batch modify your photos and metadata e.g. aaphoto, exiv2
+echo -e "Running: Photos - Install batch photos utilties - ./scripts/install-photo-utils"
 
-sudo apt install -y aaphoto exiv2 gthumb libimage-exiftool-perl
+sudo apt-get install -y aaphoto exiv2 gthumb libimage-exiftool-perl
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-qalculate b/scripts/install-qalculate
--- a/scripts/install-qalculate
+++ b/scripts/install-qalculate
@@ -1,5 +1,14 @@
 # install-qalculate
 # Useful - Install Qalculate scientific calculator
 # Install Qalculate scientific calculator
+echo -e "Running: Useful - Install Qalculate scientific calculator - ./scripts/install-qalculate"
 
-sudo apt install -y qalculate
+sudo apt-get install -y qalculate-gtk
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-qownnotes b/scripts/install-qownnotes
--- a/scripts/install-qownnotes
+++ b/scripts/install-qownnotes
@@ -1,7 +1,16 @@
 # install-qownnotes
 # Documents - Install QownNotes
 # Install notepad with markdown support and todo list manager supporting sync.
+echo -e "Running: Documents - Install QownNotes - ./scripts/install-qownnotes"
 
-sudo add-apt-repository -y ppa:pbek/qownnotes
-sudo apt update
-sudo apt install -y qownnotes
+sudo add-apt-repository -y ppa:pbek/qownnotes &&
+sudo apt-get update &&
+sudo apt-get install -y qownnotes
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-qtcreator b/scripts/install-qtcreator
--- a/scripts/install-qtcreator
+++ b/scripts/install-qtcreator
@@ -1,5 +1,14 @@
 # install-qtcreator
 # IDE - Install qtCreator IDE
 # Install IDE for qt programs
+echo -e "Running: IDE - Install qtCreator IDE - ./scripts/install-qtcreator"
 
-sudo apt install -y qtcreator
+sudo apt-get install -y qtcreator
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-scanner-support b/scripts/install-scanner-support
--- a/scripts/install-scanner-support
+++ b/scripts/install-scanner-support
@@ -1,5 +1,14 @@
 # install-scanner-support
 # Hardware - Install scanner support
 # Install utilties to support scanner in Ubuntu.
+echo -e "Running: Hardware - Install scanner support - ./scripts/install-scanner-support"
 
-sudo apt install -y xsane simple-scan
+sudo apt-get install -y xsane simple-scan
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-slack b/scripts/install-slack
--- a/scripts/install-slack
+++ b/scripts/install-slack
@@ -1,5 +1,14 @@
 # install-slack
 # Useful - Install Slack
 # Install Slack team collaboration tool from snap package.
+echo -e "Running: Useful - Install Slack - ./scripts/install-slack"
 
 sudo snap install slack --classic
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-synaptic b/scripts/install-synaptic
--- a/scripts/install-synaptic
+++ b/scripts/install-synaptic
@@ -1,5 +1,14 @@
 # install-synaptic
 # Utilties - Install Synaptic package manager
 # Install Synaptic package manager
+echo -e "Running: Utilties - Install Synaptic package manager - ./scripts/install-synaptic"
 
-sudo apt install -y synaptic
+sudo apt-get install -y synaptic
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-taskcoach b/scripts/install-taskcoach
--- a/scripts/install-taskcoach
+++ b/scripts/install-taskcoach
@@ -1,19 +1,20 @@
 # install-taskcoach
 # Useful - Install task manager – TaskCoach (using AppImage)
 # Install powerful task manager TaskCoach (using AppImage)
+echo -e "Running: Useful - Install task manager – TaskCoach (using AppImage) - ./scripts/install-taskcoach"
 
 TASKCOACH_VERSION="1.4.6"
 APPIMAGES_PATH="/home/$USER/.local/bin"
 
 ## Create directory for AppImage images
-mkdir -p $APPIMAGES_PATH
+mkdir -p $APPIMAGES_PATH &&
 
 ## Add PATH for AppImage entries
 echo -e "# Setup AppImage
 # ---------
 if [[ ! \"\$PATH\" == *$APPIMAGES_PATH* ]]; then
   export PATH=\"\${PATH:+\${PATH}:}$APPIMAGES_PATH\"
-fi" > /home/$USER/.appimage.bash
+fi" > /home/$USER/.appimage.bash &&
 
 ## AppImage entry to .bashrc (if not exist)
 if ! grep -Fxq "[ -f ~/.appimage.bash ] && source ~/.appimage.bash" /home/$USER/.bashrc
@@ -23,13 +24,13 @@ then
 fi
 
 ## Download AppImage
-wget -P /tmp https://sourceforge.net/projects/taskcoach/files/taskcoach/Release-$TASKCOACH_VERSION/TaskCoach-$TASKCOACH_VERSION-x86_64.AppImage
-mv /tmp/TaskCoach-$TASKCOACH_VERSION-x86_64.AppImage $APPIMAGES_PATH
-chmod +x $APPIMAGES_PATH/TaskCoach-$TASKCOACH_VERSION-x86_64.AppImage
+wget -P /tmp https://sourceforge.net/projects/taskcoach/files/taskcoach/Release-$TASKCOACH_VERSION/TaskCoach-$TASKCOACH_VERSION-x86_64.AppImage &&
+mv /tmp/TaskCoach-$TASKCOACH_VERSION-x86_64.AppImage $APPIMAGES_PATH &&
+chmod +x $APPIMAGES_PATH/TaskCoach-$TASKCOACH_VERSION-x86_64.AppImage &&
 
 ## Download icon
-wget -O /tmp/taskcoach.ico https://sourceforge.net/p/taskcoach/repo/ci/default/tree/taskcoach/icons.in/taskcoach.ico?format=raw
-mv /tmp/taskcoach.ico $APPIMAGES_PATH/
+wget -O /tmp/taskcoach.ico https://sourceforge.net/p/taskcoach/repo/ci/default/tree/taskcoach/icons.in/taskcoach.ico?format=raw &&
+mv /tmp/taskcoach.ico $APPIMAGES_PATH/ &&
 
 ## Add firejail configuration (if installed and user is able to use firejail) for AppImage
 if [[ $(dpkg-query -W -f='${Status}' firejail 2>/dev/null | grep -c "ok installed") -eq 1 ]] && [[ `cat /etc/firejail/firejail.users` == *$USER* ]];
@@ -40,7 +41,7 @@ else
 fi
 
 ## Integrate TaskCoach AppImage with desktop
-mkdir -p /home/$USER/.local/share/applications
+mkdir -p /home/$USER/.local/share/applications &&
 echo -e "[Desktop Entry]\n\
 Type=Application\n\
 Name=Task Coach\n\
@@ -48,3 +49,11 @@ Icon=$APPIMAGES_PATH/taskcoach.ico\n\
 Exec=$APPIMAGE_EXEC\n\
 Terminal=false\n\
 Comment=Task Coach Your Friendly Task Manager" | tee /home/$USER/.local/share/applications/taskcoach.desktop > /dev/null
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-tellico b/scripts/install-tellico
--- a/scripts/install-tellico
+++ b/scripts/install-tellico
@@ -1,6 +1,15 @@
 # install-tellico
 # Useful - Install Tellico – collections manager
 # Install Tellico – collections manager – books, movies, coins etc.
+echo -e "Running: Useful - Install Tellico – collections manager - ./scripts/install-tellico"
 
 # http://tellico-project.org/
-sudo apt install -y tellico
+sudo apt-get install -y tellico
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-thunderbird b/scripts/install-thunderbird
--- a/scripts/install-thunderbird
+++ b/scripts/install-thunderbird
@@ -1,6 +1,7 @@
 # install-thunderbird
 # Useful - Install Thunderbird
 # Install Thunderbird mail client
+echo -e "Running: Useful - Install Thunderbird - ./scripts/install-thunderbird"
 
 # Get system language (locale)
 SYS_LANGUAGE=`locale | grep LANG | cut -d= -f2 | cut -d_ -f1`
@@ -10,4 +11,12 @@ if [[ $SYS_LANGUAGE == "C.UTF-8" ]] ; then
   SYS_LANGUAGE="en"
 fi
 
-sudo apt install -y thunderbird thunderbird-gnome-support thunderbird-locale-en thunderbird-locale-$SYS_LANGUAGE
+sudo apt-get install -y thunderbird thunderbird-gnome-support thunderbird-locale-en thunderbird-locale-$SYS_LANGUAGE
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-virtualbox b/scripts/install-virtualbox
--- a/scripts/install-virtualbox
+++ b/scripts/install-virtualbox
@@ -1,5 +1,14 @@
 # install-virtualbox
 # Developer - Install VirtualBox
 # Install Virtualbox virtual machines manager.
+echo -e "Running: Developer - Install VirtualBox - ./scripts/install-virtualbox"
 
-sudo apt install -y virtualbox virtualbox-guest-additions-iso
+sudo apt-get install -y virtualbox virtualbox-guest-additions-iso
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/install-vs-code b/scripts/install-vs-code
--- a/scripts/install-vs-code
+++ b/scripts/install-vs-code
@@ -1,11 +1,20 @@
 # install-vs-code
 # IDE - Install Visual Studio Code IDE
 # Install Visual Studio Code - easy, customizable and powerful IDE for almost all languages.
+echo -e "Running: IDE - Install Visual Studio Code IDE - ./scripts/install-vs-code"
 
-wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
-sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
-sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
+wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg &&
+sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/ &&
+sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list' &&
 
-sudo apt update
-sudo apt install -y apt-transport-https
-sudo apt install -y code
+sudo apt-get update &&
+sudo apt-get install -y apt-transport-https &&
+sudo apt-get install -y code
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/perform-upgrade b/scripts/perform-upgrade
--- a/scripts/perform-upgrade
+++ b/scripts/perform-upgrade
@@ -1,6 +1,15 @@
 # perform-upgrade
 # 0Upgrade - Upgrade packages
 # Perform apt dist-upgrade
+echo -e "Running: 0Upgrade - Upgrade packages - ./scripts/perform-upgrade"
 
-sudo apt update
+sudo apt-get update &&
 sudo apt dist-upgrade -y
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/replace-gedit-pluma b/scripts/replace-gedit-pluma
--- a/scripts/replace-gedit-pluma
+++ b/scripts/replace-gedit-pluma
@@ -1,11 +1,20 @@
 # replace-gedit-pluma
 # System - Replace notepad gedit with pluma
 # Replace default gedit with powerful pluma notepad.
+echo -e "Running: System - Replace notepad gedit with pluma - ./scripts/replace-gedit-pluma"
 
-sudo apt install -y pluma
+sudo apt-get install -y pluma &&
 
 # Set as default notepad
-sudo sed -i 's/gedit.desktop/pluma.desktop/g' /etc/gnome/defaults.list
+sudo sed -i 's/gedit.desktop/pluma.desktop/g' /etc/gnome/defaults.list &&
 
 # Uninstall gedit
-sudo apt remove -y --purge gedit*
+sudo apt-get remove -y --purge gedit
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/replace-snap-packages b/scripts/replace-snap-packages
--- a/scripts/replace-snap-packages
+++ b/scripts/replace-snap-packages
@@ -1,9 +1,18 @@
 # replace-snap-packages
 # Utilties - Replace default snap packages with native Gnome apps.
 # Replace default snap packages with native Gnome apps.
+echo -e "Running: Utilties - Replace default snap packages with native Gnome apps. - ./scripts/replace-snap-packages"
 
 # Remove snaps of Gnome Calculator and Gnome System Monitor
-sudo snap remove gnome-calculator gnome-system-monitor gnome-logs gnome-characters
+sudo snap remove gnome-calculator gnome-system-monitor gnome-logs gnome-characters &&
 
 # Replace with native apps
-sudo apt install -y gnome-calculator gnome-system-monitor gnome-logs
+sudo apt-get install -y gnome-calculator gnome-system-monitor gnome-logs
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/set-grub b/scripts/set-grub
--- a/scripts/set-grub
+++ b/scripts/set-grub
@@ -1,6 +1,15 @@
 # set-grub
 # System - Set Grub Timeout to 1 second
 # Set Grub Timeout to 1 second
+echo -e "Running: System - Set Grub Timeout to 1 second - ./scripts/set-grub"
 
-sudo sed -i 's/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=1/' /etc/default/grub
+sudo sed -i 's/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=1/' /etc/default/grub &&
 sudo update-grub
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/show-hidden-autostart-entries b/scripts/show-hidden-autostart-entries
--- a/scripts/show-hidden-autostart-entries
+++ b/scripts/show-hidden-autostart-entries
@@ -1,6 +1,15 @@
 # show-hidden-autostart-entries
 # System - Show hidden autostart system entries
 # Show hidden autostart system entries
+echo -e "Running: System - Show hidden autostart system entries - ./scripts/show-hidden-autostart-entries"
 
 # Script will change flag `NoDisplay` to show system defined startup application
 sudo sed -i 's/NoDisplay=true/NoDisplay=false/g' /etc/xdg/autostart/*.desktop
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/uninstall-garbage-packages b/scripts/uninstall-garbage-packages
--- a/scripts/uninstall-garbage-packages
+++ b/scripts/uninstall-garbage-packages
@@ -1,8 +1,9 @@
 # uninstall-garbage-packages
 # Cleanup - Uninstall garbage Gnome and Ubuntu packages
 # Uninstall some garbage packages e.g. orca, shotwell, rhythmbox, totem, transmission
+echo -e "Running: Cleanup - Uninstall garbage Gnome and Ubuntu packages - ./scripts/uninstall-garbage-packages"
 
-sudo apt remove -y --purge aisleriot branding-ubuntu cheese deja-dup example-content gnome-calendar gnome-initial-setup gnome-mahjongg gnome-mines gnome-shell-extension-appindicator gnome-sudoku gnome-todo gnome-todo-common libgnome-todo orca remmina remmina-common remmina-plugin-rdp remmina-plugin-secret remmina-plugin-vnc rhythmbox rhythmbox-data rhythmbox-plugin-alternative-toolbar rhythmbox-plugins shotwell shotwell-common simple-scan totem totem-common totem-plugins transmission-common transmission-gtk ubuntu-advantage-tools ubuntu-desktop ubuntu-report ubuntu-web-launchers usb-creator-gtk vino zeitgeist-core
+sudo apt-get remove -y --purge aisleriot branding-ubuntu cheese deja-dup example-content gnome-calendar gnome-initial-setup gnome-mahjongg gnome-mines gnome-shell-extension-appindicator gnome-sudoku gnome-todo gnome-todo-common libgnome-todo orca remmina remmina-common remmina-plugin-rdp remmina-plugin-secret remmina-plugin-vnc rhythmbox rhythmbox-data rhythmbox-plugin-alternative-toolbar rhythmbox-plugins shotwell shotwell-common simple-scan totem totem-common totem-plugins transmission-common transmission-gtk ubuntu-desktop ubuntu-report usb-creator-gtk vino zeitgeist-core &&
 
 # Get system language (locale)
 SYS_LANGUAGE=`locale | grep LANG | cut -d= -f2 | cut -d_ -f1`
@@ -13,8 +14,16 @@ if [[ $SYS_LANGUAGE == "C.UTF-8" ]] ; then
 fi
 
 # uninstall non-english language packages
-sudo apt remove --purge -y `dpkg-query -W --showformat='${Package}\n' | grep language-pack | egrep -v '\-en' | egrep -v "$SYS_LANGUAGE"`
-sudo apt remove --purge -y `dpkg-query -W --showformat='${Package}\n' | grep firefox-locale | egrep -v '\-en' | egrep -v "$SYS_LANGUAGE"`
-sudo apt remove --purge -y `dpkg-query -W --showformat='${Package}\n' | grep thunderbird-locale | egrep -v '\-en' | egrep -v "$SYS_LANGUAGE"`
-sudo apt remove --purge -y `dpkg-query -W --showformat='${Package}\n' | grep libreoffice-help | egrep -v '\-en' | egrep -v "$SYS_LANGUAGE"`
-sudo apt remove --purge -y `dpkg-query -W --showformat='${Package}\n' | grep libreoffice-l10n | egrep -v '\-en' | egrep -v "$SYS_LANGUAGE"`
+sudo apt-get remove -y --purge `dpkg-query -W --showformat='${Package}\n' | grep language-pack | egrep -v '\-en' | egrep -v "$SYS_LANGUAGE"` &&
+sudo apt-get remove -y --purge `dpkg-query -W --showformat='${Package}\n' | grep firefox-locale | egrep -v '\-en' | egrep -v "$SYS_LANGUAGE"` &&
+sudo apt-get remove -y --purge `dpkg-query -W --showformat='${Package}\n' | grep thunderbird-locale | egrep -v '\-en' | egrep -v "$SYS_LANGUAGE"` &&
+sudo apt-get remove -y --purge `dpkg-query -W --showformat='${Package}\n' | grep libreoffice-help | egrep -v '\-en' | egrep -v "$SYS_LANGUAGE"` &&
+sudo apt-get remove -y --purge `dpkg-query -W --showformat='${Package}\n' | grep libreoffice-l10n | egrep -v '\-en' | egrep -v "$SYS_LANGUAGE"`
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/uninstall-old-1604-dependencies b/scripts/uninstall-old-1604-dependencies
--- a/scripts/uninstall-old-1604-dependencies
+++ b/scripts/uninstall-old-1604-dependencies
@@ -1,10 +1,19 @@
 # uninstall-old-1604-dependencies
 # Cleanup - Uninstall Ubuntu 16.04 old dependencies.
 # Uninstall 16.04 garbage dependencies after upgrade to 18.04.
+echo -e "Running: Cleanup - Uninstall Ubuntu 16.04 old dependencies. - ./scripts/uninstall-old-1604-dependencies"
 
-sudo apt remove --purge -y account-plugin-*
-sudo apt remove --purge -y libaccount-plugin-*
-sudo apt remove --purge -y flashplugin-installer
-sudo apt remove --purge -y libunity-* unity-accessibility-profiles unity-asset-pool unity-greeter unity-lens-* unity-schemas unity-scope* 
-sudo apt remove --purge -y xserver-.*-16.04
-sudo apt autoremove -y
+sudo apt-get remove -y --purge account-plugin-*
+sudo apt-get remove -y --purge libaccount-plugin-*
+sudo apt-get remove -y --purge flashplugin-installer
+sudo apt-get remove -y --purge libunity-* unity-accessibility-profiles unity-asset-pool unity-greeter unity-lens-* unity-schemas unity-scope*
+sudo apt-get remove -y --purge xserver-.*-16.04
+sudo apt-get autoremove -y
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
diff --git a/scripts/uninstall-ubuntu-dock b/scripts/uninstall-ubuntu-dock
--- a/scripts/uninstall-ubuntu-dock
+++ b/scripts/uninstall-ubuntu-dock
@@ -1,5 +1,14 @@
 # uninstall-ubuntu-dock
 # Cleanup - Uninstall Ubuntu dock
 # Uninstall Ubuntu Gnome dock.
+echo -e "Running: Cleanup - Uninstall Ubuntu dock - ./scripts/uninstall-ubuntu-dock"
 
-sudo apt remove -y --purge gnome-shell-extension-ubuntu-dock
+sudo apt-get remove -y --purge gnome-shell-extension-ubuntu-dock
+
+if [ $? -eq 0 ]; then
+   echo -e "\\nOK\\n"
+   exit 0
+else
+   echo -e "\\nFAIL\\n"
+   exit 1
+fi
